const fs = require('fs');
const path = require('path');

const files = [
  path.join(__dirname, 'frontend/src/app/departments/page.tsx'),
  path.join(__dirname, 'frontend/src/app/employees/page.tsx'),
  path.join(__dirname, 'frontend/src/app/expenses/page.tsx'),
  path.join(__dirname, 'frontend/src/app/payroll/page.tsx'),
  path.join(__dirname, 'frontend/src/app/reports/page.tsx')
];

const translations = {
  // Common
  "إلغاء": "{locale === 'ar' ? 'إلغاء' : 'Cancel'}",
  "تعديل": "{locale === 'ar' ? 'تعديل' : 'Edit'}",
  "حذف": "{locale === 'ar' ? 'حذف' : 'Delete'}",
  "حفظ التعديلات": "{locale === 'ar' ? 'حفظ التعديلات' : 'Save Changes'}",
  "مثال": "{locale === 'ar' ? 'مثال' : 'Example'}",
  "جاري التحميل": "{locale === 'ar' ? 'جاري التحميل' : 'Loading...'}",
  "جاري تحميل": "{locale === 'ar' ? 'جاري تحميل' : 'Loading...'}",
  "حدث خطأ": "{locale === 'ar' ? 'حدث خطأ' : 'An error occurred'}",
  "'حدث خطأ'": "locale === 'ar' ? 'حدث خطأ' : 'An error occurred'",
  "'فشل الحذف'": "locale === 'ar' ? 'فشل الحذف' : 'Failed to delete'",
  
  // Departments
  "'حدث خطأ أثناء حفظ القسم'": "locale === 'ar' ? 'حدث خطأ أثناء حفظ القسم' : 'Error saving department'",
  "'هل أنت متأكد من حذف هذا القسم؟ سيتم فصل الموظفين المنتسبين له'": "locale === 'ar' ? 'هل أنت متأكد من حذف هذا القسم؟ سيتم فصل الموظفين المنتسبين له' : 'Are you sure you want to delete this department? Associated employees will be unassigned'",
  "'فشل حذف القسم'": "locale === 'ar' ? 'فشل حذف القسم' : 'Failed to delete department'",
  "إدارة الأقسام": "{locale === 'ar' ? 'إدارة الأقسام' : 'Departments Management'}",
  "إجمالي الأقسام": "{locale === 'ar' ? 'إجمالي الأقسام' : 'Total Departments'}",
  "إجمالي الموظفين": "{locale === 'ar' ? 'إجمالي الموظفين' : 'Total Employees'}",
  "إضافة قسم جديد": "{locale === 'ar' ? 'إضافة قسم جديد' : 'Add New Department'}",
  "جاري تحميل الأقسام": "{locale === 'ar' ? 'جاري تحميل الأقسام' : 'Loading departments...'}",
  "لا توجد أقسام مضافة بعد": "{locale === 'ar' ? 'لا توجد أقسام مضافة بعد' : 'No departments added yet'}",
  "إضافة أول قسم": "{locale === 'ar' ? 'إضافة أول قسم' : 'Add first department'}",
  "موظف منتسب": "{locale === 'ar' ? 'موظف منتسب' : 'Associated Employee'}",
  "تعديل القسم": "{locale === 'ar' ? 'تعديل القسم' : 'Edit Department'}",
  "اسم القسم": "{locale === 'ar' ? 'اسم القسم' : 'Department Name'}",
  "قسم المبيعات": "{locale === 'ar' ? 'قسم المبيعات' : 'Sales Department'}",
  "وصف القسم": "{locale === 'ar' ? 'وصف القسم' : 'Department Description'}",
  "اختياري": "{locale === 'ar' ? 'اختياري' : 'Optional'}",
  "وصف مختصر لمهام هذا القسم": "{locale === 'ar' ? 'وصف مختصر لمهام هذا القسم' : 'Brief description of department tasks'}",
  "إضافة القسم": "{locale === 'ar' ? 'إضافة القسم' : 'Add Department'}",

  // Employees
  "'تم تعديل بيانات الموظف بنجاح'": "locale === 'ar' ? 'تم تعديل بيانات الموظف بنجاح' : 'Employee data updated successfully'",
  "'تم إضافة الموظف بنجاح'": "locale === 'ar' ? 'تم إضافة الموظف بنجاح' : 'Employee added successfully'",
  "'هل أنت متأكد من حذف هذا الموظف؟'": "locale === 'ar' ? 'هل أنت متأكد من حذف هذا الموظف؟' : 'Are you sure you want to delete this employee?'",
  "إدارة الموظفين": "{locale === 'ar' ? 'إدارة الموظفين' : 'Employees Management'}",
  "إجمالي الرواتب الأساسية": "{locale === 'ar' ? 'إجمالي الرواتب الأساسية' : 'Total Basic Salaries'}",
  "عدد الأقسام": "{locale === 'ar' ? 'عدد الأقسام' : 'Number of Departments'}",
  "بحث بالاسم أو رقم الهوية": "{locale === 'ar' ? 'بحث بالاسم أو رقم الهوية' : 'Search by name or ID'}",
  "كل الأقسام": "{locale === 'ar' ? 'كل الأقسام' : 'All Departments'}",
  "إضافة موظف جديد": "{locale === 'ar' ? 'إضافة موظف جديد' : 'Add New Employee'}",
  "لا يوجد موظفون مطابقون للبحث": "{locale === 'ar' ? 'لا يوجد موظفون مطابقون للبحث' : 'No employees matching the search'}",
  "الاسم الكامل": "{locale === 'ar' ? 'الاسم الكامل' : 'Full Name'}",
  "القسم": "{locale === 'ar' ? 'القسم' : 'Department'}",
  "رقم الهوية": "{locale === 'ar' ? 'رقم الهوية' : 'National ID'}",
  "بطاقة السكن": "{locale === 'ar' ? 'بطاقة السكن' : 'Residence Card'}",
  "الراتب الأساسي": "{locale === 'ar' ? 'الراتب الأساسي' : 'Basic Salary'}",
  "المستندات": "{locale === 'ar' ? 'المستندات' : 'Documents'}",
  "العمليات": "{locale === 'ar' ? 'العمليات' : 'Actions'}",
  "أضيف": "{locale === 'ar' ? 'أضيف' : 'Added'}",
  "هوية أ": "{locale === 'ar' ? 'هوية أ' : 'Front ID'}",
  "هوية خ": "{locale === 'ar' ? 'هوية خ' : 'Back ID'}",
  "وثائق": "{locale === 'ar' ? 'وثائق' : 'Documents'}",
  "لا يوجد": "{locale === 'ar' ? 'لا يوجد' : 'None'}",
  "استعراض": "{locale === 'ar' ? 'استعراض' : 'Browse'}",
  "بيانات الموظف": "{locale === 'ar' ? 'بيانات الموظف' : 'Employee Data'}",
  "'بدون قسم'": "locale === 'ar' ? 'بدون قسم' : 'No Department'",
  "المستندات والوثائق": "{locale === 'ar' ? 'المستندات والوثائق' : 'Documents'}",
  "صورة الهوية الأمامية": "{locale === 'ar' ? 'صورة الهوية الأمامية' : 'Front ID Image'}",
  "هوية أمامية": "{locale === 'ar' ? 'هوية أمامية' : 'Front ID'}",
  "صورة الهوية الخلفية": "{locale === 'ar' ? 'صورة الهوية الخلفية' : 'Back ID Image'}",
  "هوية خلفية": "{locale === 'ar' ? 'هوية خلفية' : 'Back ID'}",
  "تحميل الوثائق الأخرى": "{locale === 'ar' ? 'تحميل الوثائق الأخرى' : 'Upload Other Documents'}",
  "لا توجد وثائق مرفقة": "{locale === 'ar' ? 'لا توجد وثائق مرفقة' : 'No attached documents'}",
  "تعديل بيانات الموظف": "{locale === 'ar' ? 'تعديل بيانات الموظف' : 'Edit Employee Data'}",
  "البيانات الشخصية": "{locale === 'ar' ? 'البيانات الشخصية' : 'Personal Data'}",
  "الاسم الرباعي للموظف": "{locale === 'ar' ? 'الاسم الرباعي للموظف' : 'Employee Full Name'}",
  "رقم الهوية الوطنية": "{locale === 'ar' ? 'رقم الهوية الوطنية' : 'National ID Number'}",
  "رقم بطاقة السكن": "{locale === 'ar' ? 'رقم بطاقة السكن' : 'Residence Card Number'}",
  "بيانات العمل": "{locale === 'ar' ? 'بيانات العمل' : 'Work Data'}",
  "اختر القسم": "{locale === 'ar' ? 'اختر القسم' : 'Select Department'}",
  "انقر لرفع صورة": "{locale === 'ar' ? 'انقر لرفع صورة' : 'Click to upload image'}",
  "وثائق أخرى": "{locale === 'ar' ? 'وثائق أخرى' : 'Other Documents'}",
  "صورة": "{locale === 'ar' ? 'صورة' : 'Image'}",
  "انقر لرفع ملف": "{locale === 'ar' ? 'انقر لرفع ملف' : 'Click to upload file'}",
  "إضافة الموظف": "{locale === 'ar' ? 'إضافة الموظف' : 'Add Employee'}",

  // Expenses
  "عنوان المصروف": "{locale === 'ar' ? 'عنوان المصروف' : 'Expense Title'}",
  "نوع المصروف": "{locale === 'ar' ? 'نوع المصروف' : 'Expense Type'}",
  "القيمة": "{locale === 'ar' ? 'القيمة' : 'Amount'}",
  "تاريخ الدفع": "{locale === 'ar' ? 'تاريخ الدفع' : 'Payment Date'}",
  "الاستحقاق": "{locale === 'ar' ? 'الاستحقاق' : 'Due Date'}",
  "الجهة المستلمة": "{locale === 'ar' ? 'الجهة المستلمة' : 'Recipient'}",
  "المدفوع له": "{locale === 'ar' ? 'المدفوع له' : 'Payee'}",
  "حالة السداد": "{locale === 'ar' ? 'حالة السداد' : 'Payment Status'}",
  "ملاحظات وتفاصيل": "{locale === 'ar' ? 'ملاحظات وتفاصيل' : 'Notes & Details'}",
  "المصاريف التشغيلية": "{locale === 'ar' ? 'المصاريف التشغيلية' : 'Operational Expenses'}",
  "'خطأ في تصدير البيانات إلى Excel'": "locale === 'ar' ? 'خطأ في تصدير البيانات إلى Excel' : 'Error exporting data to Excel'",
  "جاري تحميل سندات ومستندات الصرف التشغيلي": "{locale === 'ar' ? 'جاري تحميل سندات ومستندات الصرف التشغيلي' : 'Loading operational expense vouchers...'}",
  "إدارة المصاريف التشغيلية": "{locale === 'ar' ? 'إدارة المصاريف التشغيلية' : 'Operational Expenses Management'}",
  "أدوات التصفية والبحث": "{locale === 'ar' ? 'أدوات التصفية والبحث' : 'Filtering and Search Tools'}",
  "تسجيل مصروف تشغيلي": "{locale === 'ar' ? 'تسجيل مصروف تشغيلي' : 'Record Operational Expense'}",
  "تصدير الكشف": "{locale === 'ar' ? 'تصدير الكشف' : 'Export Statement'}",
  "جميع أنواع المصاريف": "{locale === 'ar' ? 'جميع أنواع المصاريف' : 'All Expense Types'}",
  "جميع الحالات المالية": "{locale === 'ar' ? 'جميع الحالات المالية' : 'All Financial Statuses'}",
  "إجمالي المصاريف التشغيلية": "{locale === 'ar' ? 'إجمالي المصاريف التشغيلية' : 'Total Operational Expenses'}",
  "فواتير المياه والكهرباء والنت": "{locale === 'ar' ? 'فواتير المياه والكهرباء والنت' : 'Water, Electricity, and Internet Bills'}",
  "المواصلات والمستلزمات المكتبية": "{locale === 'ar' ? 'المواصلات والمستلزمات المكتبية' : 'Transportation and Office Supplies'}",
  "مسير كشوفات وسجلات الصرف التشغيلي": "{locale === 'ar' ? 'مسير كشوفات وسجلات الصرف التشغيلي' : 'Operational Expenses Statements and Records'}",
  "لا توجد سجلات مصاريف مطابقة للتصفية الحالية": "{locale === 'ar' ? 'لا توجد سجلات مصاريف مطابقة للتصفية الحالية' : 'No expense records match the current filter'}",
  "عنوان السند": "{locale === 'ar' ? 'عنوان السند' : 'Voucher Title'}",
  "النوع والتصنيف": "{locale === 'ar' ? 'النوع والتصنيف' : 'Type & Category'}",
  "القيمة المالية": "{locale === 'ar' ? 'القيمة المالية' : 'Financial Value'}",
  "تاريخ السند": "{locale === 'ar' ? 'تاريخ السند' : 'Voucher Date'}",
  "العمليات الإجرائية": "{locale === 'ar' ? 'العمليات الإجرائية' : 'Procedural Operations'}",
  "تأكيد سداد السند": "{locale === 'ar' ? 'تأكيد سداد السند' : 'Confirm Voucher Payment'}",
  "تعديل السند": "{locale === 'ar' ? 'تعديل السند' : 'Edit Voucher'}",
  "حذف السند": "{locale === 'ar' ? 'حذف السند' : 'Delete Voucher'}",
  "تعديل سند الصرف التشغيلي": "{locale === 'ar' ? 'تعديل سند الصرف التشغيلي' : 'Edit Operational Expense Voucher'}",
  "سند صرف مصروف تشغيلي جديد": "{locale === 'ar' ? 'سند صرف مصروف تشغيلي جديد' : 'New Operational Expense Voucher'}",
  "البيان": "{locale === 'ar' ? 'البيان' : 'Statement'}",
  "فاتورة مياه وكهرباء الفرع الرئيسي": "{locale === 'ar' ? 'فاتورة مياه وكهرباء الفرع الرئيسي' : 'Main Branch Water & Electricity Bill'}",
  "نوع وتصنيف المصروف": "{locale === 'ar' ? 'نوع وتصنيف المصروف' : 'Expense Type & Category'}",
  "تاريخ الصرف": "{locale === 'ar' ? 'تاريخ الصرف' : 'Payment Date'}",
  "المبلغ المالي": "{locale === 'ar' ? 'المبلغ المالي' : 'Financial Amount'}",
  "مصلحة المياه والكهرباء": "{locale === 'ar' ? 'مصلحة المياه والكهرباء' : 'Water and Electricity Authority'}",
  "حالة السداد المالية": "{locale === 'ar' ? 'حالة السداد المالية' : 'Financial Payment Status'}",
  "تم الدفع": "{locale === 'ar' ? 'تم الدفع' : 'Paid'}",
  "سند مدفوع": "{locale === 'ar' ? 'سند مدفوع' : 'Paid Voucher'}",
  "سند مستحق": "{locale === 'ar' ? 'سند مستحق' : 'Due Voucher'}",
  "ملاحظات وتفاصيل إضافية": "{locale === 'ar' ? 'ملاحظات وتفاصيل إضافية' : 'Additional Notes & Details'}",
  "تسجيل السند المالي": "{locale === 'ar' ? 'تسجيل السند المالي' : 'Record Financial Voucher'}",
  "'هل أنت متأكد من حذف هذا السند المالي بشكل نهائي؟'": "locale === 'ar' ? 'هل أنت متأكد من حذف هذا السند المالي بشكل نهائي؟' : 'Are you sure you want to permanently delete this financial voucher?'",

  // Payroll
  "'تم تعديل سجل الرواتب بنجاح'": "locale === 'ar' ? 'تم تعديل سجل الرواتب بنجاح' : 'Payroll record updated successfully'",
  "'تم إضافة سجل الرواتب بنجاح'": "locale === 'ar' ? 'تم إضافة سجل الرواتب بنجاح' : 'Payroll record added successfully'",
  "'حدث خطأ أثناء حفظ السجل، يرجى التأكد من البيانات المدخلة'": "locale === 'ar' ? 'حدث خطأ أثناء حفظ السجل، يرجى التأكد من البيانات المدخلة' : 'Error saving record, please check entered data'",
  "'فشل الاتصال بالخادم'": "locale === 'ar' ? 'فشل الاتصال بالخادم' : 'Failed to connect to server'",
  "'تم حذف سجل الرواتب بنجاح'": "locale === 'ar' ? 'تم حذف سجل الرواتب بنجاح' : 'Payroll record deleted successfully'",
  "'خطأ في الاتصال بالخادم'": "locale === 'ar' ? 'خطأ في الاتصال بالخادم' : 'Server connection error'",
  "'هل تريد تأكيد صرف راتب الموظف '": "locale === 'ar' ? 'هل تريد تأكيد صرف راتب الموظف ' : 'Do you want to confirm salary payment for employee '",
  "' لشهر '": "locale === 'ar' ? ' لشهر ' : ' for month '",
  "'تم تأكيد صرف الراتب بنجاح وتسجيل تاريخ الصرف اللحظي'": "locale === 'ar' ? 'تم تأكيد صرف الراتب بنجاح وتسجيل تاريخ الصرف اللحظي' : 'Salary payment confirmed successfully and instantaneous payment date recorded'",
  "'فشل تحديث حالة الصرف'": "locale === 'ar' ? 'فشل تحديث حالة الصرف' : 'Failed to update payment status'",
  "اسم الموظف": "{locale === 'ar' ? 'اسم الموظف' : 'Employee Name'}",
  "الشهر": "{locale === 'ar' ? 'الشهر' : 'Month'}",
  "الحوافز والبونص": "{locale === 'ar' ? 'الحوافز والبونص' : 'Incentives & Bonus'}",
  "العمل الإضافي": "{locale === 'ar' ? 'العمل الإضافي' : 'Overtime'}",
  "التأمينات الاجتماعية": "{locale === 'ar' ? 'التأمينات الاجتماعية' : 'Social Insurance'}",
  "خصم": "{locale === 'ar' ? 'خصم' : 'Deduction'}",
  "صافي الراتب": "{locale === 'ar' ? 'صافي الراتب' : 'Net Salary'}",
  "مخصصات نهاية الخدمة": "{locale === 'ar' ? 'مخصصات نهاية الخدمة' : 'End of Service Benefits'}",
  "تم الصرف": "{locale === 'ar' ? 'تم الصرف' : 'Paid'}",
  "قيد الانتظار": "{locale === 'ar' ? 'قيد الانتظار' : 'Pending'}",
  "ملاحظات": "{locale === 'ar' ? 'ملاحظات' : 'Notes'}",
  "مسير الرواتب والأجور": "{locale === 'ar' ? 'مسير الرواتب والأجور' : 'Payroll & Wages'}",
  "جاري تحميل مسير الرواتب والمستحقات الماليّة": "{locale === 'ar' ? 'جاري تحميل مسير الرواتب والمستحقات الماليّة' : 'Loading payroll and financial dues...'}",
  "إدارة مسير الرواتب والمستحقات الماليّة": "{locale === 'ar' ? 'إدارة مسير الرواتب والمستحقات الماليّة' : 'Payroll & Financial Dues Management'}",
  "إضافة سجل مالي": "{locale === 'ar' ? 'إضافة سجل مالي' : 'Add Financial Record'}",
  "تصدير كشف الرواتب": "{locale === 'ar' ? 'تصدير كشف الرواتب' : 'Export Payroll Statement'}",
  "إجمالي صافي الرواتب المصروفة": "{locale === 'ar' ? 'إجمالي صافي الرواتب المصروفة' : 'Total Net Paid Salaries'}",
  "إجمالي الحوافز والبونص": "{locale === 'ar' ? 'إجمالي الحوافز والبونص' : 'Total Incentives & Bonus'}",
  "إجمالي العمل الإضافي": "{locale === 'ar' ? 'إجمالي العمل الإضافي' : 'Total Overtime'}",
  "التأمينات الاجتماعية المستقطعة": "{locale === 'ar' ? 'التأمينات الاجتماعية المستقطعة' : 'Deducted Social Insurance'}",
  "إجمالي الرواتب بحسب القسم": "{locale === 'ar' ? 'إجمالي الرواتب بحسب القسم' : 'Total Salaries by Department'}",
  "سجلات وكشوفات الرواتب والأجور": "{locale === 'ar' ? 'سجلات وكشوفات الرواتب والأجور' : 'Payroll & Wages Records'}",
  "لا توجد سجلات رواتب مدخلة لهذا الشهر": "{locale === 'ar' ? 'لا توجد سجلات رواتب مدخلة لهذا الشهر' : 'No payroll records entered for this month'}",
  "التأمينات": "{locale === 'ar' ? 'التأمينات' : 'Insurance'}",
  "حالة الصرف": "{locale === 'ar' ? 'حالة الصرف' : 'Payment Status'}",
  "شهر": "{locale === 'ar' ? 'شهر' : 'Month'}",
  "صرف": "{locale === 'ar' ? 'صرف' : 'Pay'}",
  "تأكيد صرف الراتب": "{locale === 'ar' ? 'تأكيد صرف الراتب' : 'Confirm Salary Payment'}",
  "تعديل السجل": "{locale === 'ar' ? 'تعديل السجل' : 'Edit Record'}",
  "حذف السجل": "{locale === 'ar' ? 'حذف السجل' : 'Delete Record'}",
  "تعديل السجل المالي للموظف": "{locale === 'ar' ? 'تعديل السجل المالي للموظف' : 'Edit Employee Financial Record'}",
  "إضافة سجل مالي جديد لموظف": "{locale === 'ar' ? 'إضافة سجل مالي جديد لموظف' : 'Add New Financial Record for Employee'}",
  "اختيار الموظف": "{locale === 'ar' ? 'اختيار الموظف' : 'Select Employee'}",
  "اختر الموظف من القائمة": "{locale === 'ar' ? 'اختر الموظف من القائمة' : 'Select Employee from List'}",
  "الشهر المستهدف": "{locale === 'ar' ? 'الشهر المستهدف' : 'Target Month'}",
  "استقطاع": "{locale === 'ar' ? 'استقطاع' : 'Deduction'}",
  "اتركه فارغاً للحساب التلقائي": "{locale === 'ar' ? 'اتركه فارغاً للحساب التلقائي' : 'Leave empty for automatic calculation'}",
  "الحالة الإبتدائية": "{locale === 'ar' ? 'الحالة الإبتدائية' : 'Initial Status'}",
  "حساب مستحق": "{locale === 'ar' ? 'حساب مستحق' : 'Due Account'}",
  "تم الصرف فوراً": "{locale === 'ar' ? 'تم الصرف فوراً' : 'Paid Immediately'}",
  "ملاحظات وتفاصيل الدفع": "{locale === 'ar' ? 'ملاحظات وتفاصيل الدفع' : 'Payment Notes & Details'}",
  "إدراج السجل المالي": "{locale === 'ar' ? 'إدراج السجل المالي' : 'Insert Financial Record'}",

  // Reports
  "'تأمين السيارات'": "locale === 'ar' ? 'تأمين السيارات' : 'Auto Insurance'",
  "'تأمين صحي'": "locale === 'ar' ? 'تأمين صحي' : 'Health Insurance'",
  "'تأمين على الحياة'": "locale === 'ar' ? 'تأمين على الحياة' : 'Life Insurance'",
  "'تأمين الممتلكات'": "locale === 'ar' ? 'تأمين الممتلكات' : 'Property Insurance'",
  "'تأمين السفر'": "locale === 'ar' ? 'تأمين السفر' : 'Travel Insurance'",
  "'تأمين النقل والبحري'": "locale === 'ar' ? 'تأمين النقل والبحري' : 'Marine & Transport Insurance'",
  "'تأمين ضد الحريق'": "locale === 'ar' ? 'تأمين ضد الحريق' : 'Fire Insurance'",
  "'تأمين المسؤولية'": "locale === 'ar' ? 'تأمين المسؤولية' : 'Liability Insurance'",
  "'غير معروف'": "locale === 'ar' ? 'غير معروف' : 'Unknown'",
  "'لا توجد وثائق من نوع '": "locale === 'ar' ? 'لا توجد وثائق من نوع ' : 'No policies of type '",
  "' في الفترة المحددة لتصديرها.'": "locale === 'ar' ? ' في الفترة المحددة لتصديرها.' : ' in the specified period for export.'",
  "العميل": "{locale === 'ar' ? 'العميل' : 'Client'}",
  "نوع التأمين": "{locale === 'ar' ? 'نوع التأمين' : 'Insurance Type'}",
  "مبلغ القسط": "{locale === 'ar' ? 'مبلغ القسط' : 'Premium Amount'}",
  "مبلغ التغطية": "{locale === 'ar' ? 'مبلغ التغطية' : 'Coverage Amount'}",
  "العملة": "{locale === 'ar' ? 'العملة' : 'Currency'}",
  "تاريخ الإصدار": "{locale === 'ar' ? 'تاريخ الإصدار' : 'Issue Date'}",
  "تاريخ الانتهاء": "{locale === 'ar' ? 'تاريخ الانتهاء' : 'Expiry Date'}",
  "حالة الوثيقة": "{locale === 'ar' ? 'حالة الوثيقة' : 'Policy Status'}",
  "تاريخ الإضافة": "{locale === 'ar' ? 'تاريخ الإضافة' : 'Addition Date'}",
  "المستخدم المدخل": "{locale === 'ar' ? 'المستخدم المدخل' : 'Entered By'}",
  "'إيرادات '": "locale === 'ar' ? 'إيرادات ' : 'Revenues '",
  "'لا توجد مطالبات/خسائر من نوع '": "locale === 'ar' ? 'لا توجد مطالبات/خسائر من نوع ' : 'No claims/losses of type '",
  "الخسارة": "{locale === 'ar' ? 'الخسارة' : 'Loss'}",
  "خسارة معتمدة": "{locale === 'ar' ? 'خسارة معتمدة' : 'Approved Loss'}",
  "تاريخ التقديم": "{locale === 'ar' ? 'تاريخ التقديم' : 'Submission Date'}",
  "'خسائر '": "locale === 'ar' ? 'خسائر ' : 'Losses '",
  "'لا يوجد بيانات لتصديرها'": "locale === 'ar' ? 'لا يوجد بيانات لتصديرها' : 'No data to export'",
  "رقم التعريفي": "{locale === 'ar' ? 'رقم التعريفي' : 'ID Number'}",
  "المدخل": "{locale === 'ar' ? 'المدخل' : 'Entered By'}",
  "'تقرير العملاء'": "locale === 'ar' ? 'تقرير العملاء' : 'Clients Report'",
  "'محتمل'": "locale === 'ar' ? 'محتمل' : 'Lead'",
  "'تقرير العملاء المحتملين'": "locale === 'ar' ? 'تقرير العملاء المحتملين' : 'Leads Report'",
  "النوع": "{locale === 'ar' ? 'النوع' : 'Type'}",
  "'أخرى'": "locale === 'ar' ? 'أخرى' : 'Other'",
  "'دينار عراقي'": "locale === 'ar' ? 'دينار عراقي' : 'IQD'",
  "'دولار أمريكي'": "locale === 'ar' ? 'دولار أمريكي' : 'USD'",
  "'تقرير الوثائق'": "locale === 'ar' ? 'تقرير الوثائق' : 'Policies Report'",
  "الوصف": "{locale === 'ar' ? 'الوصف' : 'Description'}",
  "'تقرير المطالبات'": "locale === 'ar' ? 'تقرير المطالبات' : 'Claims Report'",
  "لا يوجد خسائر": "{locale === 'ar' ? 'لا يوجد خسائر' : 'No losses'}",
  "آمن ومربح ممتاز": "{locale === 'ar' ? 'آمن ومربح ممتاز' : 'Safe and Highly Profitable'}",
  "مخاطر معتدلة مقبولة": "{locale === 'ar' ? 'مخاطر معتدلة مقبولة' : 'Acceptable Moderate Risks'}",
  "خسائر مرتفعة": "{locale === 'ar' ? 'خسائر مرتفعة' : 'High Losses'}",
  "حرجة": "{locale === 'ar' ? 'حرجة' : 'Critical'}",
  "التقارير وتحليل الأداء المالي": "{locale === 'ar' ? 'التقارير وتحليل الأداء المالي' : 'Reports & Financial Performance Analysis'}",
  "المؤشرات المالية والتحليلات": "{locale === 'ar' ? 'المؤشرات المالية والتحليلات' : 'Financial Indicators & Analysis'}",
  "استخراج التقارير العامة": "{locale === 'ar' ? 'استخراج التقارير العامة' : 'Extract General Reports'}",
  "تصفية التقارير المالية والتحليلات": "{locale === 'ar' ? 'تصفية التقارير المالية والتحليلات' : 'Filter Financial Reports & Analytics'}",
  "فترة التحليل المالي": "{locale === 'ar' ? 'فترة التحليل المالي' : 'Financial Analysis Period'}",
  "جميع الأوقات": "{locale === 'ar' ? 'جميع الأوقات' : 'All Time'}",
  "تاريخ تراكمي": "{locale === 'ar' ? 'تاريخ تراكمي' : 'Cumulative Date'}",
  "آخر 30 يوم": "{locale === 'ar' ? 'آخر 30 يوم' : 'Last 30 Days'}",
  "آخر 3 أشهر": "{locale === 'ar' ? 'آخر 3 أشهر' : 'Last 3 Months'}",
  "آخر سنة": "{locale === 'ar' ? 'آخر سنة' : 'Last Year'}",
  "تحديد فترة مخصصة": "{locale === 'ar' ? 'تحديد فترة مخصصة' : 'Specify Custom Period'}",
  "من تاريخ": "{locale === 'ar' ? 'من تاريخ' : 'From Date'}",
  "إلى تاريخ": "{locale === 'ar' ? 'إلى تاريخ' : 'To Date'}",
  "إيرادات أقساط التأمين المكتتبة": "{locale === 'ar' ? 'إيرادات أقساط التأمين المكتتبة' : 'Written Premium Revenues'}",
  "وثيقة صادرة خلال الفترة": "{locale === 'ar' ? 'وثيقة صادرة خلال الفترة' : 'Policy issued during period'}",
  "التعويضات والخسائر المعتمدة": "{locale === 'ar' ? 'التعويضات والخسائر المعتمدة' : 'Approved Compensations & Losses'}",
  "مطالبة مقبولة ومدفوعة": "{locale === 'ar' ? 'مطالبة مقبولة ومدفوعة' : 'Accepted and Paid Claim'}",
  "صافي الإيراد التشغيلي": "{locale === 'ar' ? 'صافي الإيراد التشغيلي' : 'Net Operating Income'}",
  "الفائض": "{locale === 'ar' ? 'الفائض' : 'Surplus'}",
  "بعد خصم الخسائر المسددة من الإيرادات": "{locale === 'ar' ? 'بعد خصم الخسائر المسددة من الإيرادات' : 'After deducting paid losses from revenues'}",
  "معدل الخسارة الإجمالي": "{locale === 'ar' ? 'معدل الخسارة الإجمالي' : 'Total Loss Ratio'}",
  "تقرير إيرادات وثائق التأمين": "{locale === 'ar' ? 'تقرير إيرادات وثائق التأمين' : 'Insurance Policies Revenue Report'}",
  "حسب النوع": "{locale === 'ar' ? 'حسب النوع' : 'By Type'}",
  "مجموع مبالغ الأقساط ونسب المساهمة المالية لكل نوع تأمين": "{locale === 'ar' ? 'مجموع مبالغ الأقساط ونسب المساهمة المالية لكل نوع تأمين' : 'Total premium amounts and financial contribution rates for each insurance type'}",
  "عدد الوثائق الصادرة": "{locale === 'ar' ? 'عدد الوثائق الصادرة' : 'Number of Issued Policies'}",
  "إجمالي الإيرادات": "{locale === 'ar' ? 'إجمالي الإيرادات' : 'Total Revenues'}",
  "الأقساط": "{locale === 'ar' ? 'الأقساط' : 'Premiums'}",
  "نسبة المساهمة من المبيعات": "{locale === 'ar' ? 'نسبة المساهمة من المبيعات' : 'Sales Contribution Percentage'}",
  "تصدير ملخص الإيرادات": "{locale === 'ar' ? 'تصدير ملخص الإيرادات' : 'Export Revenue Summary'}",
  "عدد الوثائق النشطة": "{locale === 'ar' ? 'عدد الوثائق النشطة' : 'Number of Active Policies'}",
  "إجمالي إيرادات الأقساط": "{locale === 'ar' ? 'إجمالي إيرادات الأقساط' : 'Total Premium Revenues'}",
  "نسبة المساهمة المالية": "{locale === 'ar' ? 'نسبة المساهمة المالية' : 'Financial Contribution Percentage'}",
  "التحميل والاستخراج": "{locale === 'ar' ? 'التحميل والاستخراج' : 'Download and Extraction'}",
  "تصدير كشف إيرادات": "{locale === 'ar' ? 'تصدير كشف إيرادات' : 'Export Revenue Statement'}",
  "تقرير الخسائر ومطالبات التعويض": "{locale === 'ar' ? 'تقرير الخسائر ومطالبات التعويض' : 'Losses & Compensation Claims Report'}",
  "تحليل المطالبات المعتمدة": "{locale === 'ar' ? 'تحليل المطالبات المعتمدة' : 'Analysis of Approved Claims'}",
  "الخسائر المدفوعة": "{locale === 'ar' ? 'الخسائر المدفوعة' : 'Paid Losses'}",
  "ونسب الخسارة مقابل الأقساط": "{locale === 'ar' ? 'ونسب الخسارة مقابل الأقساط' : 'and loss ratios against premiums'}",
  "المطالبات المقدمة": "{locale === 'ar' ? 'المطالبات المقدمة' : 'Submitted Claims'}",
  "الخسائر المعتمدة": "{locale === 'ar' ? 'الخسائر المعتمدة' : 'Approved Losses'}",
  "المدفوعة": "{locale === 'ar' ? 'المدفوعة' : 'Paid'}",
  "معدل الخسارة": "{locale === 'ar' ? 'معدل الخسارة' : 'Loss Ratio'}",
  "مستوى تقييم الخسارة": "{locale === 'ar' ? 'مستوى تقييم الخسارة' : 'Loss Evaluation Level'}",
  "تقرير خسائر ومطالبات التأمين": "{locale === 'ar' ? 'تقرير خسائر ومطالبات التأمين' : 'Insurance Losses & Claims Report'}",
  "تصدير ملخص الخسائر": "{locale === 'ar' ? 'تصدير ملخص الخسائر' : 'Export Loss Summary'}",
  "الخسائر المعتمدة المعتمدة": "{locale === 'ar' ? 'الخسائر المعتمدة المعتمدة' : 'Approved Losses'}",
  "معدل خسارة التأمين": "{locale === 'ar' ? 'معدل خسارة التأمين' : 'Insurance Loss Ratio'}",
  "درجة الخطورة": "{locale === 'ar' ? 'درجة الخطورة' : 'Risk Level'}",
  "مطالبات": "{locale === 'ar' ? 'مطالبات' : 'Claims'}",
  "تصدير تفاصيل الخسائر": "{locale === 'ar' ? 'تصدير تفاصيل الخسائر' : 'Export Loss Details'}",
  "الفترة الزمنية": "{locale === 'ar' ? 'الفترة الزمنية' : 'Time Period'}",
  "مخصص": "{locale === 'ar' ? 'مخصص' : 'Custom'}",
  "اختيار تواريخ": "{locale === 'ar' ? 'اختيار تواريخ' : 'Select Dates'}",
  "استخراج تقرير العملاء": "{locale === 'ar' ? 'استخراج تقرير العملاء' : 'Extract Clients Report'}",
  "استخراج العملاء المحتملين": "{locale === 'ar' ? 'استخراج العملاء المحتملين' : 'Extract Leads Report'}",
  "تقرير كافة الوثائق": "{locale === 'ar' ? 'تقرير كافة الوثائق' : 'All Policies Report'}",
  "جميع الحالات": "{locale === 'ar' ? 'جميع الحالات' : 'All Statuses'}",
  "شارفت على الانتهاء": "{locale === 'ar' ? 'شارفت على الانتهاء' : 'Nearing Expiry'}",
  "خلال 30 يوم": "{locale === 'ar' ? 'خلال 30 يوم' : 'Within 30 Days'}",
  "استخراج تقرير الوثائق": "{locale === 'ar' ? 'استخراج تقرير الوثائق' : 'Extract Policies Report'}",
  "تقرير كافة المطالبات": "{locale === 'ar' ? 'تقرير كافة المطالبات' : 'All Claims Report'}",
  "استخراج تقرير المطالبات": "{locale === 'ar' ? 'استخراج تقرير المطالبات' : 'Extract Claims Report'}",
  "تأمين السيارات": "{locale === 'ar' ? 'تأمين السيارات' : 'Auto Insurance'}",
  "تأمين صحي": "{locale === 'ar' ? 'تأمين صحي' : 'Health Insurance'}",
  "تأمين على الحياة": "{locale === 'ar' ? 'تأمين على الحياة' : 'Life Insurance'}",
  "تأمين الممتلكات": "{locale === 'ar' ? 'تأمين الممتلكات' : 'Property Insurance'}",
  "تأمين السفر": "{locale === 'ar' ? 'تأمين السفر' : 'Travel Insurance'}",
  "تأمين النقل والبحري": "{locale === 'ar' ? 'تأمين النقل والبحري' : 'Marine & Transport Insurance'}",
  "تأمين ضد الحريق": "{locale === 'ar' ? 'تأمين ضد الحريق' : 'Fire Insurance'}",
  "تأمين المسؤولية": "{locale === 'ar' ? 'تأمين المسؤولية' : 'Liability Insurance'}",
  "غير معروف": "{locale === 'ar' ? 'غير معروف' : 'Unknown'}"
};

files.forEach(file => {
  if (!fs.existsSync(file)) return;
  let content = fs.readFileSync(file, 'utf8');

  // Add import if not exists
  if (!content.includes('useLanguage')) {
    content = content.replace(
      'import { useEffect, useState } from \'react\';',
      "import { useEffect, useState } from 'react';\nimport { useLanguage } from '../components/LanguageContext';"
    );
  }

  // Add hook inside component if not exists
  const funcMatch = content.match(/export default function (Departments|Employees|Expenses|Payroll|Reports)\(\) \{/);
  if (funcMatch && !content.includes('const { locale } = useLanguage();')) {
    content = content.replace(
      funcMatch[0],
      funcMatch[0] + "\n  const { locale } = useLanguage();"
    );
  }

  // Regular strings replacement
  // Sort by length to avoid replacing sub-strings first
  const sortedTranslations = Object.entries(translations).sort((a, b) => b[0].length - a[0].length);

  for (const [key, value] of sortedTranslations) {
    if (key.startsWith("'") && key.endsWith("'")) {
      const escapedKey = key.replace(/[-\/\\^$*+?.()|[\]{}]/g, '\\$&');
      content = content.replace(new RegExp(escapedKey, 'g'), value);
    } else {
      // For JSX text nodes
      const escapedKey = key.replace(/[-\/\\^$*+?.()|[\]{}]/g, '\\$&');
      content = content.replace(new RegExp('>' + escapedKey + '<', 'g'), '>' + value + '<');
    }
  }

  // Additional attribute strings and inline conditions
  content = content.replace(/placeholder="بحث في الأقسام..."/g, "placeholder={locale === 'ar' ? 'بحث في الأقسام...' : 'Search departments...'}");
  content = content.replace(/placeholder="بحث بالاسم أو رقم الهوية..."/g, "placeholder={locale === 'ar' ? 'بحث بالاسم أو رقم الهوية...' : 'Search by name or ID...'}");
  content = content.replace(/placeholder="بحث في عنوان المصروف أو الجهة المدفوع لها..."/g, "placeholder={locale === 'ar' ? 'بحث في عنوان المصروف أو الجهة المدفوع لها...' : 'Search expense title or payee...'}");
  content = content.replace(/placeholder="أدخل أي ملاحظات إجرائية حول السداد..."/g, "placeholder={locale === 'ar' ? 'أدخل أي ملاحظات إجرائية حول السداد...' : 'Enter payment notes...'}");
  content = content.replace(/placeholder="أدخل أي ملاحظات بخصوص بدلات العمل الإضافي أو البونص..."/g, "placeholder={locale === 'ar' ? 'أدخل أي ملاحظات بخصوص بدلات العمل الإضافي أو البونص...' : 'Enter notes regarding overtime or bonus...'}");
  
  content = content.replace(/ \? 'نشط' : 'غير نشط'/g, " ? (locale === 'ar' ? 'نشط' : 'Active') : (locale === 'ar' ? 'غير نشط' : 'Inactive')");

  fs.writeFileSync(file, content, 'utf8');
  console.log('Translated ' + file);
});
