"use client";

import React, { createContext, useContext, useState, useEffect } from 'react';

type Locale = 'ar' | 'en';

const translations = {
  ar: {
    appName: "POLICYHUB",
    appSubtitle: "نظام إدارة التأمين",
    dashboard: "لوحة التحكم",
    staffManagement: "لوحة المدير ",
    customers: "العملاء",
    dataEntry: "إدخال البيانات",
    policies: "الوثائق",
    leads: "العملاء المحتملين",
    claims: "المطالبات",
    reports: "التقارير",
    payroll: "الرواتب والأجور",
    expenses: "المصاريف التشغيلية",
    logout: "تسجيل الخروج",
    goodMorning: "صباح الخير،",
    systemTitle: "نظام إدارة التأمين الشامل",
    systemDescription: "أهلاً بك في منصتك المتكاملة لإدارة أعمال شركة التأمين. تم تصميم هذا النظام ليوفر لك كل ما تحتاجه لإدارة العملاء، الوثائق، والمطالبات بكفاءة وسهولة تامة.",
    crmTitle: "إدارة العملاء (CRM)",
    crmDescription: "تتبع بيانات عملائك وسجل التواصل معهم بكل احترافية، مع لوحة تحكم ذكية لفهم احتياجاتهم بشكل أفضل.",
    enterSystem: "دخول للنظام",
    policyTitle: "وثائق التأمين",
    policyDescription: "إصدار وتجديد وتعديل وثائق التأمين المختلفة (سيارات، صحي، الخ) مع متابعة الأقساط المالية بدقة.",
    managePolicies: "إدارة الوثائق",
    claimsTitle: "نظام المطالبات",
    claimsDescription: "استقبل المطالبات من العملاء، راجعها، وقم باتخاذ القرارات اللازمة من خلال سير عمل مبسط ومنظم.",
    trackClaims: "متابعة المطالبات",
    dataEntryTitle: "واجهة إدخال البيانات",
    addClient: "إضافة عميل",
    issuePolicy: "إصدار وثيقة",
    addClientNew: "إضافة عميل جديد",
    addCompanyNew: "إضافة شركة جديدة",
    individual: "فردي",
    corporate: "شركة",
    firstName: "الاسم الأول *",
    secondName: "الاسم الثاني *",
    thirdName: "الاسم الثالث *",
    lastName: "اللقب (اختياري)",
    motherName: "اسم الأم (اختياري)",
    grandfatherName: "اسم الجد من الأم (اختياري)",
    nationalId: "رقم الهوية",
    dob: "تاريخ الميلاد",
    email: "البريد الإلكتروني (اختياري)",
    phone: "رقم الهاتف *",
    phone2: "رقم هاتف إضافي",
    address: "العنوان *",
    saveClient: "حفظ العميل",
    companyName: "اسم الشركة (عربي / إنكليزي) *",
    companyType: "نوع الشركة *",
    government: "حكومية",
    privateSec: "قطاع خاص",
    mixed: "قطاع مشترك",
    industry: "مجال النشاط *",
    foundationDate: "تاريخ التأسيس",
    chamberOfCommerce: "رقم غرفة التجارة (إن وجد)",
    registrationNumber: "رقم التسجيل في دائرة تسجيل الشركات",
    governorate: "المحافظة *",
    officialEmail: "البريد الإلكتروني الرسمي *",
    officialPhone: "رقم الموبايل *",
    detailedAddress: "العنوان التفصيلي",
    policyIssueTitle: "إصدار وثيقة تأمين",
    policyApprovalNotice: "سيتم إرسال الوثيقة للمدير للموافقة عليها",
    selectClient: "اختر العميل...",
    policyNumber: "رقم الوثيقة *",
    policyType: "نوع الوثيقة",
    startDate: "تاريخ البدء",
    endDate: "تاريخ الانتهاء",
    coverageAmount: "مبلغ التغطية",
    premiumAmount: "مبلغ القسط *",
    deductible: "مبلغ التحمل",
    paymentFrequency: "دورية الدفع",
    paymentMethod: "طريقة الدفع",
    beneficiaryName: "اسم المستفيد",
    beneficiaryRelation: "صلة القرابة",
    insuredItemDetails: "تفاصيل الشيء المؤمن عليه...",
    notes: "ملاحظات...",
    submitApproval: "إرسال للموافقة",
    required: "هذا الحقل مطلوب",
    phoneLengthError: "يجب أن يتكون من 11 رقم",
    phoneDuplicateError: "رقم الهاتف مكرر لايمكن اضافة عميل",
    emailInvalidError: "صيغة البريد الإلكتروني غير صحيحة",
    addressRequired: "العنوان مطلوب",
    clientAddedSuccess: "تم إضافة العميل بنجاح!",
    policySubmittedSuccess: "تم إرسال الوثيقة للموافقة!",
    saveError: "خطأ في الحفظ",
    settings: "الإعدادات",
    profile: "الملف الشخصي",
    activePolicies: "الوثائق النشطة",
    languageLabel: "English",
    termsAndExclusions: "الشروط والاستثناءات",
    employees: "الموظفون",
    departments: "الأقسام",
    hrManagement: "الموارد البشرية",
    brokers: "المناديب والوسطاء",
    brokerCommissions: "نظام العمولات",
    welcomeDesc: "مرحباً بك في نظام إدارة التأمين الشامل",
    totalClients: "إجمالي العملاء",
    activePoliciesCount: "الوثائق الفعالة",
    totalPremiums: "إجمالي الأقساط المحصلة",
    salesLast6Months: "المبيعات في آخر 6 أشهر",
    totalPremiumCurrency: "إجمالي الأقساط (دينار/دولار)",
    policyDistribution: "توزيع الوثائق حسب النوع",
    loadingStats: "جاري تحميل الإحصائيات...",
    remindersTitle: "التنبيهات: وثائق تنتهي قريباً",
    remindersSubtitle: "Notifications / Renewals",
    remindersWarning: "هذه القائمة تعرض الوثائق الفعالة التي ستنتهي خلال 60 يوماً. يرجى التواصل مع العملاء لتجديدها.",
    loadingReminders: "جاري تحميل التنبيهات...",
    noReminders: "لا توجد وثائق تنتهي خلال الـ 60 يوماً القادمة",
    policyNo: "وثيقة رقم:",
    expiredSince: "منتهية منذ",
    days: "يوم",
    endsToday: "تنتهي اليوم",
    remaining: "باقي",
    expiryDate: "تاريخ الانتهاء",
    netPremium: "القسط الصافي",
    callToRenew: "اتصل للتجديد",
    brokersTitle: "إدارة المناديب والوسطاء ",
    brokersSubtitle: "CRM / Brokers",
    addBroker: "إضافة مندوب جديد",
    loadingBrokers: "جاري تحميل البيانات...",
    noBrokers: "لا يوجد مناديب مضافين بعد",
    addFirstBroker: "إضافة أول مندوب",
    phoneNotSpecified: "غير محدد",
    defaultCommission: "العمولة الافتراضية المقطوعة لكل وثيقة",
    editBroker: "تعديل المندوب",
    brokerName: "اسم المندوب / الوسيط *",
    phoneOptional: "رقم الهاتف (اختياري)",
    commissionAmount: "المبلغ المقطوع الافتراضي للعمولة *",
    commissionDesc: "سيتم استخدام هذا المبلغ تلقائياً عند اختيار المندوب في وثيقة التأمين.",
    saveChanges: "حفظ التعديلات",
    cancel: "إلغاء",
    commissionPercentage: "نسبة العمولة (%)",
    brokerEarnings: "أرباح المندوب (إجمالي العمولات)",
    brokerPolicies: "بوالص التأمين المقترنة",
    viewProfile: "عرض الملف الشخصي",
    brokerProfile: "ملف المندوب / الوسيط",
    totalEarnings: "إجمالي الأرباح:",
    noPoliciesLinked: "لا توجد بوالص تأمين مرتبطة بهذا المندوب حالياً.",
    brokerSelect: "اختر المندوب / الوسيط",
    typeAuto: "سيارات",
    typeHealth: "صحي",
    typeLife: "حياة",
    typeProperty: "ممتلكات",
    typeTravel: "سفر",
    typeMarine: "بحري",
    typeFire: "حريق",
    typeLiability: "مسؤولية",
    typeEngineering: "تأمين هندسي",
    statusActive: "مفعّلة",
    statusExpired: "منتهية",
    statusCancelled: "ملغاة",
    statusPending: "تم الرفع (Draft)",
    statusUnderReview: "قيد التدقيق",
    statusApproved: "تمت الموافقة فنيّاً",
    statusRejected: "مرفوضة فنيّاً",
    statusAwaitingPayment: "بانتظار الدفع",
    statusSuspended: "معلقة",
    freqMonthly: "شهري",
    freqQuarterly: "ربع سنوي",
    freqSemiAnnual: "نصف سنوي",
    freqAnnual: "سنوي",
    freqOneTime: "دفعة واحدة",
    payCash: "نقدي",
    payBank: "تحويل بنكي",
    payCredit: "بطاقة ائتمان",
    payCheck: "شيك",
    msgEditSuccess: "تم التعديل بنجاح. الوثيقة الآن قيد الموافقة.",
    msgAddSuccess: "تمت الإضافة بنجاح. الوثيقة الآن قيد الموافقة.",
    msgConfirmApprove: "هل أنت متأكد من الموافقة على هذه الوثيقة وتفعيلها؟",
    msgApproveSuccess: "تمت الموافقة بنجاح",
    msgApproveError: "حدث خطأ أثناء الموافقة",
    msgRenewSuccess: "تم تجديد الوثيقة بنجاح وإرسالها للموافقة (قيد الموافقة).",
    msgRenewError: "حدث خطأ أثناء التجديد",
    pendingPoliciesTab: "قيد الموافقة",
    allPoliciesTab: "كل الوثائق",
    policiesAwaitingApproval: "وثائق تنتظر موافقتك",
    noPendingPolicies: "لا توجد وثائق قيد الانتظار ",
    openPolicy: "فتح الوثيقة",
    approve: "موافقة",
    reject: "رفض",
    clientLabel: "العميل:",
    premiumLabel: "القسط:",
    coverageLabel: "التغطية:",
    fromLabel: "من",
    toLabel: "إلى",
    allPolicies: "جميع الوثائق",
    actions: "إجراءات",
    addClaim: "إضافة مطالبة",
    claimNumber: "رقم المطالبة",
    amount: "المبلغ",
    claimStatusApproved: "مقبولة",
    claimStatusRejected: "مرفوضة",
    claimStatusReview: "قيد المراجعة",
    claimantInfo: "معلومات المطالب",
    addNewClaim: "إضافة مطالبة جديدة",
    searchPolicyOrClient: "ابحث برقم الوثيقة أو اسم العميل...",
    noMatchingPolicies: "لا توجد وثائق مطابقة ",
    claimAmount: "مبلغ المطالبة *",
    claimDescription: "وصف المطالبة *",
    saveClaim: "حفظ المطالبة",
    totalCoverage: "إجمالي التغطية",
    status: "الحالة",
    errorSaving: "حدث خطأ أثناء الحفظ",
    confirmDelete: "هل أنت متأكد من الحذف؟",
    errorDeleting: "حدث خطأ أثناء الحذف",
    edit: "تعديل",
    delete: "حذف"
  },
  en: {
    appName: "POLICYHUB",
    appSubtitle: "Insurance Management",
    dashboard: "Dashboard",
    staffManagement: " Management",
    customers: "Customers",
    dataEntry: "Data Entry",
    policies: "Policies",
    leads: "Leads",
    claims: "Claims",
    reports: "Reports",
    payroll: "Payroll",
    expenses: "Expenses",
    logout: "Logout",
    goodMorning: "Good morning,",
    systemTitle: "Comprehensive Insurance System",
    systemDescription: "Welcome to your integrated platform for managing insurance operations. This system is designed to provide you with everything you need to manage clients, policies, and claims efficiently and easily.",
    crmTitle: "Client Management (CRM)",
    crmDescription: "Track your clients' data and communication history professionally, with a smart dashboard to better understand their needs.",
    enterSystem: "Enter CRM",
    policyTitle: "Insurance Policies",
    policyDescription: "Issue, renew, and modify various insurance policies (auto, health, etc.) with precise premium tracking.",
    managePolicies: "Manage Policies",
    claimsTitle: "Claims System",
    claimsDescription: "Receive claims from clients, review them, and make necessary decisions through a simplified and organized workflow.",
    trackClaims: "Track Claims",
    dataEntryTitle: "Data Entry Interface",
    addClient: "Add Client",
    issuePolicy: "Issue Policy",
    addClientNew: "Add New Client",
    addCompanyNew: "Add New Company",
    individual: "Individual",
    corporate: "Corporate",
    firstName: "First Name *",
    secondName: "Second Name *",
    thirdName: "Third Name *",
    lastName: "Last Name (Optional)",
    motherName: "Mother Name (Optional)",
    grandfatherName: "Maternal Grandfather Name (Optional)",
    nationalId: "National ID",
    dob: "Date of Birth",
    email: "Email (Optional)",
    phone: "Phone Number *",
    phone2: "Additional Phone",
    address: "Address *",
    saveClient: "Save Client",
    companyName: "Company Name (Arabic / English) *",
    companyType: "Company Type *",
    government: "Government",
    privateSec: "Private Sector",
    mixed: "Mixed Sector",
    industry: "Industry *",
    foundationDate: "Foundation Date",
    chamberOfCommerce: "Chamber of Commerce No. (if any)",
    registrationNumber: "Registration Number",
    governorate: "Governorate *",
    officialEmail: "Official Email *",
    officialPhone: "Mobile Number *",
    detailedAddress: "Detailed Address",
    policyIssueTitle: "Issue Insurance Policy",
    policyApprovalNotice: "The policy will be sent to the manager for approval",
    selectClient: "Select Client...",
    policyNumber: "Policy Number *",
    policyType: "Policy Type",
    startDate: "Start Date",
    endDate: "End Date",
    coverageAmount: "Coverage Amount",
    premiumAmount: "Premium Amount *",
    deductible: "Deductible",
    paymentFrequency: "Payment Frequency",
    paymentMethod: "Payment Method",
    beneficiaryName: "Beneficiary Name",
    beneficiaryRelation: "Relation",
    insuredItemDetails: "Insured item details...",
    notes: "Notes...",
    submitApproval: "Submit for Approval",
    required: "This field is required",
    phoneLengthError: "Must be exactly 11 digits",
    phoneDuplicateError: "Duplicate phone number, cannot add client",
    emailInvalidError: "Invalid email format",
    addressRequired: "Address is required",
    clientAddedSuccess: "Client added successfully!",
    policySubmittedSuccess: "Policy sent for approval!",
    saveError: "Error saving",
    settings: "Settings",
    profile: "Profile",
    activePolicies: "Active Policies",
    languageLabel: "العربية",
    termsAndExclusions: "Terms & Exclusions",
    employees: "Employees",
    departments: "Departments",
    hrManagement: "HR Management",
    brokers: "Brokers & Agents",
    brokerCommissions: "Commissions System",
    welcomeDesc: "Welcome to the Comprehensive Insurance System",
    totalClients: "Total Clients",
    activePoliciesCount: "Active Policies",
    totalPremiums: "Total Collected Premiums",
    salesLast6Months: "Sales in Last 6 Months",
    totalPremiumCurrency: "Total Premium (IQD/USD)",
    policyDistribution: "Policies Distribution by Type",
    loadingStats: "Loading statistics...",
    remindersTitle: "Reminders: Expiring Policies",
    remindersSubtitle: "Notifications / Renewals",
    remindersWarning: "This list shows active policies that will expire within 60 days. Please contact clients for renewal.",
    loadingReminders: "Loading reminders...",
    noReminders: "No policies expiring in the next 60 days",
    policyNo: "Policy No:",
    expiredSince: "Expired since",
    days: "days",
    endsToday: "Ends today",
    remaining: "Remaining",
    expiryDate: "Expiry Date",
    netPremium: "Net Premium",
    callToRenew: "Call to Renew",
    brokersTitle: "Brokers & Agents Management",
    brokersSubtitle: "CRM / Brokers",
    addBroker: "Add New Broker",
    loadingBrokers: "Loading data...",
    noBrokers: "No brokers added yet",
    addFirstBroker: "Add First Broker",
    phoneNotSpecified: "Not specified",
    defaultCommission: "Default Fixed Commission per Policy",
    editBroker: "Edit Broker",
    brokerName: "Broker / Agent Name *",
    phoneOptional: "Phone Number (Optional)",
    commissionAmount: "Default Fixed Commission Amount *",
    commissionDesc: "This amount will be used automatically when selecting the broker in the policy.",
    saveChanges: "Save Changes",
    cancel: "Cancel",
    commissionPercentage: "Commission Percentage (%)",
    brokerEarnings: "Broker Earnings (Total Commissions)",
    brokerPolicies: "Associated Policies",
    viewProfile: "View Profile",
    brokerProfile: "Broker / Agent Profile",
    totalEarnings: "Total Earnings:",
    noPoliciesLinked: "No policies linked to this broker currently.",
    brokerSelect: "Select Broker / Agent",
    typeAuto: "Auto",
    typeHealth: "Health",
    typeLife: "Life",
    typeProperty: "Property",
    typeTravel: "Travel",
    typeMarine: "Marine",
    typeFire: "Fire",
    typeLiability: "Liability",
    typeEngineering: "Engineering Insurance",
    statusActive: "Active Policy",
    statusExpired: "Expired",
    statusCancelled: "Cancelled",
    statusPending: "Pending / Draft",
    statusUnderReview: "Under Review",
    statusApproved: "Approved (Underwritten)",
    statusRejected: "Rejected (Underwritten)",
    statusAwaitingPayment: "Awaiting Payment",
    statusSuspended: "Suspended",
    freqMonthly: "Monthly",
    freqQuarterly: "Quarterly",
    freqSemiAnnual: "Semi-Annual",
    freqAnnual: "Annual",
    freqOneTime: "One Time",
    payCash: "Cash",
    payBank: "Bank Transfer",
    payCredit: "Credit Card",
    payCheck: "Check",
    msgEditSuccess: "Edited successfully. Policy is now pending approval.",
    msgAddSuccess: "Added successfully. Policy is now pending approval.",
    msgConfirmApprove: "Are you sure you want to approve and activate this policy?",
    msgApproveSuccess: "Approved successfully",
    msgApproveError: "Error during approval",
    msgRenewSuccess: "Policy renewed successfully and sent for approval (pending).",
    msgRenewError: "Error during renewal",
    pendingPoliciesTab: "Pending Approval",
    allPoliciesTab: "All Policies",
    policiesAwaitingApproval: "Policies Awaiting Your Approval",
    noPendingPolicies: "No pending policies ",
    openPolicy: "Open Policy",
    approve: "Approve",
    reject: "Reject",
    clientLabel: "Client:",
    premiumLabel: "Premium:",
    coverageLabel: "Coverage:",
    fromLabel: "From",
    toLabel: "to",
    allPolicies: "All Policies",
    actions: "Actions",
    addClaim: "Add Claim",
    claimNumber: "Claim Number",
    amount: "Amount",
    claimStatusApproved: "Approved",
    claimStatusRejected: "Rejected",
    claimStatusReview: "Under Review",
    claimantInfo: "Claimant Info",
    addNewClaim: "Add New Claim",
    searchPolicyOrClient: "Search by policy number or client name...",
    noMatchingPolicies: "No matching policies 🔍",
    claimAmount: "Claim Amount *",
    claimDescription: "Claim Description *",
    saveClaim: "Save Claim",
    totalCoverage: "Total Coverage",
    status: "Status",
    errorSaving: "Error occurred while saving",
    confirmDelete: "Are you sure you want to delete?",
    errorDeleting: "Error occurred while deleting",
    edit: "Edit",
    delete: "Delete"
  }
};

interface LanguageContextType {
  locale: Locale;
  setLocale: (locale: Locale) => void;
  t: (key: keyof typeof translations['ar']) => string;
  toggleLanguage: () => void;
  isRtl: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [locale, setLocaleState] = useState<Locale>('ar');

  useEffect(() => {
    const savedLocale = localStorage.getItem('locale') as Locale;
    if (savedLocale === 'en' || savedLocale === 'ar') {
      setLocaleState(savedLocale);
    }
  }, []);

  const setLocale = (newLocale: Locale) => {
    setLocaleState(newLocale);
    localStorage.setItem('locale', newLocale);
  };

  useEffect(() => {
    document.documentElement.lang = locale;
    document.documentElement.dir = locale === 'ar' ? 'rtl' : 'ltr';
  }, [locale]);

  const toggleLanguage = () => {
    setLocale(locale === 'ar' ? 'en' : 'ar');
  };

  const t = (key: keyof typeof translations['ar']): string => {
    return translations[locale][key] || translations['en'][key] || String(key);
  };

  const isRtl = locale === 'ar';

  return (
    <LanguageContext.Provider value={{ locale, setLocale, t, toggleLanguage, isRtl }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
