# Generated by Django 6.0.5 on 2026-05-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='id_image_back',
            field=models.ImageField(blank=True, null=True, upload_to='clients/id_images/', verbose_name='صورة الهوية (الوجه الخلفي)'),
        ),
        migrations.AddField(
            model_name='client',
            name='id_image_front',
            field=models.ImageField(blank=True, null=True, upload_to='clients/id_images/', verbose_name='صورة الهوية (الوجه الأمامي)'),
        ),
        migrations.AddField(
            model_name='client',
            name='national_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الهوية'),
        ),
        migrations.AddField(
            model_name='client',
            name='other_documents',
            field=models.FileField(blank=True, null=True, upload_to='clients/documents/', verbose_name='وثائق أخرى'),
        ),
    ]
