# Generated by Django 6.0.5 on 2026-05-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_client_id_image_back_client_id_image_front_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='beneficiary_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='اسم المستفيد'),
        ),
        migrations.AddField(
            model_name='policy',
            name='beneficiary_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='هاتف المستفيد'),
        ),
        migrations.AddField(
            model_name='policy',
            name='beneficiary_relation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='صلة القرابة'),
        ),
        migrations.AddField(
            model_name='policy',
            name='coverage_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='مبلغ التغطية'),
        ),
        migrations.AddField(
            model_name='policy',
            name='deductible',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مبلغ التحمل'),
        ),
        migrations.AddField(
            model_name='policy',
            name='insured_item_details',
            field=models.TextField(blank=True, null=True, verbose_name='تفاصيل الشيء المؤمن عليه'),
        ),
        migrations.AddField(
            model_name='policy',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات'),
        ),
        migrations.AddField(
            model_name='policy',
            name='payment_frequency',
            field=models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('SEMI_ANNUAL', 'Semi-Annual'), ('ANNUAL', 'Annual'), ('ONE_TIME', 'One-Time Payment')], default='ANNUAL', max_length=20, verbose_name='دورية الدفع'),
        ),
        migrations.AddField(
            model_name='policy',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('CREDIT_CARD', 'Credit Card'), ('CHECK', 'Check')], default='CASH', max_length=20, verbose_name='طريقة الدفع'),
        ),
        migrations.AddField(
            model_name='policy',
            name='policy_document',
            field=models.FileField(blank=True, null=True, upload_to='policies/documents/', verbose_name='وثيقة البوليصة'),
        ),
        migrations.AddField(
            model_name='policy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='policy_type',
            field=models.CharField(choices=[('AUTO', 'Auto Insurance'), ('HEALTH', 'Health Insurance'), ('LIFE', 'Life Insurance'), ('PROPERTY', 'Property Insurance'), ('TRAVEL', 'Travel Insurance'), ('MARINE', 'Marine Insurance'), ('FIRE', 'Fire Insurance'), ('LIABILITY', 'Liability Insurance')], max_length=20),
        ),
        migrations.AlterField(
            model_name='policy',
            name='premium_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مبلغ القسط'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled'), ('PENDING', 'Pending Approval'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=20),
        ),
    ]
