# Generated by Django 6.0.5 on 2026-05-14 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('INDIVIDUAL', 'فردي'), ('CORPORATE', 'شركات')], default='INDIVIDUAL', max_length=20, verbose_name='تصنيف العميل'),
        ),
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('LEAD', 'عميل محتمل (Lead)'), ('ACTIVE', 'عميل نشط'), ('INACTIVE', 'عميل غير نشط')], default='LEAD', max_length=20, verbose_name='حالة العميل'),
        ),
    ]
