# Generated by Django 6.0.5 on 2026-05-14 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_client_created_by_client_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='second_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='third_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
