# Generated by Django 6.0.5 on 2026-05-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_client_second_name_client_third_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='chamber_of_commerce',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم غرفة التجارة'),
        ),
        migrations.AddField(
            model_name='client',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='اسم الشركة'),
        ),
        migrations.AddField(
            model_name='client',
            name='company_type',
            field=models.CharField(blank=True, choices=[('GOVERNMENT', 'حكومية'), ('PRIVATE', 'قطاع خاص'), ('MIXED', 'قطاع مشترك')], max_length=50, null=True, verbose_name='نوع الشركة'),
        ),
        migrations.AddField(
            model_name='client',
            name='governorate',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='المحافظة'),
        ),
        migrations.AddField(
            model_name='client',
            name='industry',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='مجال النشاط'),
        ),
        migrations.AddField(
            model_name='client',
            name='registration_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم التسجيل'),
        ),
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='second_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
