# Generated by Django 6.0.5 on 2026-05-14 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_client_chamber_of_commerce_client_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='grandfather_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم الجد'),
        ),
        migrations.AddField(
            model_name='client',
            name='mother_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم الأم'),
        ),
    ]
