# Generated by Django 6.0.5 on 2026-05-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_client_grandfather_name_client_mother_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'ذكر'), ('FEMALE', 'أنثى')], max_length=10, null=True, verbose_name='الجنس'),
        ),
        migrations.AddField(
            model_name='client',
            name='id_issue_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ إصدار الهوية'),
        ),
        migrations.AddField(
            model_name='client',
            name='id_issue_place',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='مكان إصدار الهوية'),
        ),
        migrations.AddField(
            model_name='client',
            name='passport_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم جواز السفر'),
        ),
        migrations.AddField(
            model_name='client',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='مكان الميلاد'),
        ),
    ]
