# Generated by Django 6.0.5 on 2026-05-18 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_client_gender_client_id_issue_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='annual_income',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الدخل السنوي'),
        ),
        migrations.AddField(
            model_name='client',
            name='employment_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع العمل'),
        ),
        migrations.AddField(
            model_name='client',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='المسمى الوظيفي'),
        ),
        migrations.AddField(
            model_name='client',
            name='source_of_funds',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='مصادر الأموال'),
        ),
    ]
