# Generated by Django 6.0.5 on 2026-05-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_client_annual_income_client_employment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='annual_financials',
            field=models.FileField(blank=True, null=True, upload_to='companies/financials/', verbose_name='بيانات الشركة المالية السنوية'),
        ),
        migrations.AddField(
            model_name='client',
            name='authorized_capital',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='رأس المال المصرح به'),
        ),
        migrations.AddField(
            model_name='client',
            name='ceo_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='اسم المدير التنفيذي'),
        ),
        migrations.AddField(
            model_name='client',
            name='company_annual_income',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الدخل السنوي للشركة'),
        ),
        migrations.AddField(
            model_name='client',
            name='company_nationality',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='جنسية الشركة'),
        ),
        migrations.AddField(
            model_name='client',
            name='num_branches',
            field=models.IntegerField(blank=True, null=True, verbose_name='عدد الفروع'),
        ),
        migrations.AddField(
            model_name='client',
            name='num_employees',
            field=models.IntegerField(blank=True, null=True, verbose_name='عدد الموظفين'),
        ),
        migrations.AddField(
            model_name='client',
            name='paid_capital',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='رأس المال المدفوع'),
        ),
        migrations.AddField(
            model_name='client',
            name='po_box',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم صندوق البريد'),
        ),
        migrations.AddField(
            model_name='client',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='الرمز البريدي'),
        ),
        migrations.AddField(
            model_name='client',
            name='registration_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ التسجيل'),
        ),
    ]
