# Generated by Django 6.0.5 on 2026-05-18 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_client_annual_financials_client_authorized_capital_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=150, verbose_name='اسم الموظف')),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الراتب الأساسي')),
                ('bonuses', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الحوافز والبونص')),
                ('overtime', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='العمل الإضافي')),
                ('social_security', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='التأمينات الاجتماعية')),
                ('end_of_service', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مخصصات نهاية الخدمة')),
                ('month', models.CharField(max_length=7, verbose_name='الشهر (YYYY-MM)')),
                ('payout_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الصرف')),
                ('status', models.CharField(choices=[('PENDING', 'قيد الانتظار'), ('PAID', 'تم الصرف')], default='PENDING', max_length=20, verbose_name='حالة الصرف')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payrolls', to=settings.AUTH_USER_MODEL, verbose_name='مستخدم النظام')),
            ],
        ),
    ]
