# Generated by Django 6.0.5 on 2026-05-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_payroll'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان المصروف')),
                ('expense_type', models.CharField(choices=[('RENT', 'إيجارات المكاتب أو الفروع'), ('UTILITIES', 'فواتير الكهرباء والماء والإنترنت'), ('MAINTENANCE', 'صيانة الأجهزة والمعدات'), ('TRANSPORT', 'مصاريف النقل والوقود'), ('SUPPLIES', 'مستلزمات العمل المكتبية'), ('OTHER', 'مصاريف تشغيلية أخرى')], max_length=20, verbose_name='نوع المصروف')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قيمة المصروف')),
                ('expense_date', models.DateField(verbose_name='تاريخ الاستحقاق/الدفع')),
                ('paid_to', models.CharField(blank=True, max_length=150, null=True, verbose_name='الجهة المستلمة')),
                ('status', models.CharField(choices=[('PENDING', 'قيد الانتظار'), ('PAID', 'تم الدفع')], default='PAID', max_length=20, verbose_name='حالة الدفع')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='تفاصيل وملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
