# Generated by Django 6.0.5 on 2026-05-20 16:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_claim_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='admin_fees',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='رسوم إدارية'),
        ),
        migrations.AddField(
            model_name='policy',
            name='currency',
            field=models.CharField(choices=[('IQD', 'دينار'), ('USD', 'دولار')], default='IQD', max_length=3, verbose_name='العملة'),
        ),
        migrations.AddField(
            model_name='policy',
            name='diwan_fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='قيمة رسم الديوان'),
        ),
        migrations.AddField(
            model_name='policy',
            name='diwan_fee_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة رسم الديوان (%)'),
        ),
        migrations.AddField(
            model_name='policy',
            name='issue_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاريخ الإصدار'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='policy',
            name='net_premium',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='قسط الاشتراك الصافي'),
        ),
        migrations.AddField(
            model_name='policy',
            name='stamp_duty_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='قيمة رسم الطابع'),
        ),
        migrations.AddField(
            model_name='policy',
            name='stamp_duty_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة رسم الطابع (%)'),
        ),
        migrations.AddField(
            model_name='policy',
            name='terms_and_conditions',
            field=models.TextField(blank=True, null=True, verbose_name='الشروط والأحكام'),
        ),
        migrations.AddField(
            model_name='policy',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='المبلغ الكامل'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='end_date',
            field=models.DateField(verbose_name='نهاية فترة التأمين'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='policy_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='رقم الوثيقة'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='policy_type',
            field=models.CharField(choices=[('AUTO', 'Auto Insurance'), ('HEALTH', 'Health Insurance'), ('LIFE', 'Life Insurance'), ('PROPERTY', 'Property Insurance'), ('TRAVEL', 'Travel Insurance'), ('MARINE', 'Marine Insurance'), ('FIRE', 'Fire Insurance'), ('LIABILITY', 'Liability Insurance')], max_length=20, verbose_name='نوع الوثيقة'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='premium_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='مبلغ القسط'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='start_date',
            field=models.DateField(verbose_name='بداية فترة التأمين'),
        ),
    ]
