# Generated by Django 6.0.5 on 2026-05-20 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_policy_admin_fees_policy_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='sequence_number',
            field=models.IntegerField(default=0, verbose_name='رقم تسلسلي'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='policy_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='رقم الوثيقة'),
        ),
    ]
