# Generated by Django 6.0.5 on 2026-05-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_policy_sequence_number_alter_policy_policy_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyTemplateText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان النموذج')),
                ('content', models.TextField(verbose_name='نص النموذج')),
                ('template_type', models.CharField(choices=[('TERMS', 'الشروط والأحكام'), ('EXCLUSIONS', 'الاستثناءات')], default='TERMS', max_length=20, verbose_name='نوع النموذج')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='policy',
            name='exclusions',
            field=models.TextField(blank=True, null=True, verbose_name='الاستثناءات'),
        ),
    ]
