# Generated by Django 6.0.5 on 2026-05-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_policytemplatetext_policy_exclusions'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_phones_left', models.CharField(blank=True, max_length=255, null=True, verbose_name='أرقام الشركة (يسار)')),
                ('branches_phones_right', models.CharField(blank=True, max_length=255, null=True, verbose_name='أرقام الفروع (يمين)')),
            ],
        ),
    ]
