# Generated by Django 6.0.5 on 2026-05-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0020_systemsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='branches_phones_right',
            field=models.TextField(blank=True, null=True, verbose_name='أرقام الفروع (يمين)'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='company_phones_left',
            field=models.TextField(blank=True, null=True, verbose_name='أرقام الشركة (يسار)'),
        ),
    ]
