# Generated by Django 6.0.5 on 2026-05-20 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_alter_systemsettings_branches_phones_right_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم القسم')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف القسم')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='payroll',
            name='employee_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='اسم الموظف (قديم)'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='الاسم الكامل')),
                ('national_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الهوية')),
                ('residence_card', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم بطاقة السكن')),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الراتب الأساسي')),
                ('id_image_front', models.ImageField(blank=True, null=True, upload_to='employees/id_images/', verbose_name='صورة الهوية الأمامية')),
                ('id_image_back', models.ImageField(blank=True, null=True, upload_to='employees/id_images/', verbose_name='صورة الهوية الخلفية')),
                ('other_documents', models.FileField(blank=True, null=True, upload_to='employees/documents/', verbose_name='وثائق أخرى')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='crm.department', verbose_name='القسم')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='حساب النظام')),
            ],
        ),
        migrations.AddField(
            model_name='payroll',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payrolls', to='crm.employee', verbose_name='الموظف'),
        ),
    ]
