# Generated by Django 6.0.5 on 2026-05-20 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0022_department_alter_payroll_employee_name_employee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم الوسيط/المندوب')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف')),
                ('default_commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المبلغ المقطوع الافتراضي للعمولة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='policy',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='مبلغ العمولة المقطوع'),
        ),
        migrations.AddField(
            model_name='policy',
            name='broker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policies', to='crm.broker', verbose_name='الوسيط / المندوب'),
        ),
    ]
