# Generated by Django 6.0.5 on 2026-05-20 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0023_broker_policy_commission_amount_policy_broker'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='settings/logos/', verbose_name='شعار الشركة'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='branches_phones_right',
            field=models.TextField(blank=True, null=True, verbose_name='هواتف الفروع (يمين)'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='company_phones_left',
            field=models.TextField(blank=True, null=True, verbose_name='هواتف الشركة (يسار)'),
        ),
    ]
