# Generated by Django 6.0.5 on 2026-05-21 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0024_systemsettings_company_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='car_chassis_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم الشاصي'),
        ),
        migrations.AddField(
            model_name='policy',
            name='car_color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='لون السيارة'),
        ),
        migrations.AddField(
            model_name='policy',
            name='car_engine_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم المحرك'),
        ),
        migrations.AddField(
            model_name='policy',
            name='car_model',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الموديل'),
        ),
        migrations.AddField(
            model_name='policy',
            name='car_plate_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم اللوحة'),
        ),
        migrations.AddField(
            model_name='policy',
            name='car_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع السيارة'),
        ),
        migrations.AddField(
            model_name='policy',
            name='car_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='سنة الصنع'),
        ),
    ]
