# Generated by Django 6.0.5 on 2026-05-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0025_policy_car_chassis_no_policy_car_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='car_chassis_no',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='car_color',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='car_engine_no',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='car_model',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='car_plate_number',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='car_type',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='car_year',
        ),
        migrations.AddField(
            model_name='policy',
            name='vehicles',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='المركبات المؤمنة'),
        ),
    ]
