# Generated by Django 6.0.5 on 2026-05-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0026_remove_policy_car_chassis_no_remove_policy_car_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='family_members',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='أفراد العائلة'),
        ),
        migrations.AddField(
            model_name='policy',
            name='health_coverage_details',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='تفاصيل التغطية الصحية والشبكة الطبية'),
        ),
    ]
