# Generated by Django 6.0.5 on 2026-05-21 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0027_policy_family_members_policy_health_coverage_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='property_details',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='تفاصيل الممتلكات'),
        ),
    ]
