# Generated by Django 6.0.5 on 2026-05-21 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0028_policy_property_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='engineering_details',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='التفاصيل الهندسية'),
        ),
        migrations.AddField(
            model_name='policy',
            name='engineering_equipment',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='المعدات الهندسية'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='policy_type',
            field=models.CharField(choices=[('AUTO', 'Auto Insurance'), ('HEALTH', 'Health Insurance'), ('LIFE', 'Life Insurance'), ('PROPERTY', 'Property Insurance'), ('TRAVEL', 'Travel Insurance'), ('MARINE', 'Marine Insurance'), ('FIRE', 'Fire Insurance'), ('LIABILITY', 'Liability Insurance'), ('ENGINEERING', 'Engineering Insurance')], max_length=20, verbose_name='نوع الوثيقة'),
        ),
    ]
