# Generated by Django 6.0.5 on 2026-05-21 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0029_policy_engineering_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionalOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_price', models.CharField(max_length=100, verbose_name='السعر الابتدائي')),
                ('special_discount', models.CharField(blank=True, max_length=100, null=True, verbose_name='خصم خاص')),
                ('validity_period', models.CharField(max_length=100, verbose_name='فترة العرض')),
                ('features', models.TextField(blank=True, null=True, verbose_name='المزايا')),
                ('trust_licensed', models.BooleanField(default=True, verbose_name='شركة مرخصة')),
                ('trust_clients_count', models.CharField(blank=True, max_length=100, null=True, verbose_name='عدد العملاء')),
                ('trust_years_experience', models.CharField(blank=True, max_length=100, null=True, verbose_name='سنوات الخبرة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotional_offers', to='crm.client', verbose_name='العميل المحتمل')),
            ],
        ),
    ]
