# Generated by Django 6.0.5 on 2026-05-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0030_promotionaloffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='commission_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة العمولة (%)'),
        ),
    ]
