# Generated by Django 6.0.5 on 2026-05-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0031_policy_commission_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending/Draft'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('AWAITING_PAYMENT', 'Awaiting Payment'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'مدير النظام'), ('DATA_ENTRY', 'مدخل بيانات'), ('AUDITOR', 'مدقق فني'), ('ACCOUNTANT', 'محاسب')], default='DATA_ENTRY', max_length=20),
        ),
    ]
