# Generated by Django 6.0.5 on 2026-05-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0032_alter_policy_status_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('AWAITING_PAYMENT', 'Awaiting Payment'), ('PAID', 'Paid')], default='PENDING', max_length=20),
        ),
    ]
