# Generated by Django 6.0.5 on 2026-05-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0033_alter_claim_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'مدير النظام'), ('DATA_ENTRY', 'مدخل بيانات'), ('AUDITOR', 'مدقق فني'), ('ACCOUNTANT', 'محاسب'), ('HR', 'مسؤول الموارد البشرية')], default='DATA_ENTRY', max_length=20),
        ),
    ]
